services:
  dvwa:
    image: ghcr.io/digininja/dvwa:latest
    container_name: dvwa
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    ports:
      - "127.0.0.1:8081:80"
    networks:
      - dvwa
    restart: unless-stopped

  db:
    image: mariadb:10
    container_name: dvwa-db
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped

networks:
  dvwa:

volumes:
  dvwa: